### ISSUE TITLE
Form not responsive

### ISSUE THREAD

**Issue by Shub3am** [Ebazhanov/nextjs-tailwind-landing-page#1]
Contact Form is not responsve on Mobile
![image](https://user-images.githubusercontent.com/77344771/188323037-4429a9e6-d490-4826-97d7-9372821e3736.png)

**Comment by Ebazhanov** [comment]
thank you my friend, updated https://github.com/Ebazhanov/nextjs-tailwind-landing-page/commit/c260e3684961368583fa5c1a31bfc3a624722efb
